ini_names:
  ability.ini: 技能
  buff.ini: 魔法效果
  imp.ini: 导入文件
  item.ini: 物品
  misc.ini: 平衡常数
  unit.ini: 单位
  upgrade.ini: 科技
  w3i.ini: 地图属性
user_settings:
  input_path: example/ini/Attack and defense 0.1.36-preview/table
  output_path: rundata/output
  output_filename: output
  conversion_type: ini_to_excel
